---
area/apps:
  - 'apps/**/*'
area/libs:
  - 'libs/**/*'
scope/portfolio:
  - apps/portfolio/**/*
  - apps/portfolio-e2e/**/*
  - libs/portfolio/**/*
scope/shared:
  - libs/shared/**/*
type/data-access:
  - libs/**/data-access-*/*
type/util:
  - libs/**/util*/*
type/ui:
  - libs/**/ui-*/*
dep-updates:
  - package.json
  - package-lock.json
