name: Main Branch CI

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on:
  push:
    branches:
      - 'main'

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Nx Cloud - Main Job
    if: contains(github.event.head_commit.message, '(release)') != true
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
    with:
      main-branch-name: main
      number-of-agents: 3
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        npx nx-cloud record -- npx nx format:check
        npx nx-cloud record -- npx commitlint --from ${{ github.sha }} --to ${{ github.sha }} --verbose
      parallel-commands-on-agents: |
        npx nx run-many --target=lint --all --parallel=3
        npx nx run-many --target=test --all --parallel=3 --ci --coverage --skip-nx-cache
        npx nx run-many --target=build --all --parallel=3
        npx nx run-many --target=e2e --all --parallel=1 --ci
      artifacts-path: |
        dist/
        coverage/
      artifacts-name: dist-and-coverage-artifacts

  agents:
    name: Nx Cloud - Agents
    if: contains(github.event.head_commit.message, '(release)') != true
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
    with:
      number-of-agents: 3

  codecoverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: ['main']
    steps:
      - uses: actions/checkout@v3
      - uses: xSAVIKx/artifact-exists-action@v0
        id: check-artifact-exists
        with:
          name: dist-and-coverage-artifacts
      - uses: actions/download-artifact@v3
        if: steps.check-artifact-exists.outputs.exists == 'true'
        with:
          name: dist-and-coverage-artifacts
          path: coverage/
      - uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: false # optional (default = false)

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ['codecoverage']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci
      - uses: xSAVIKx/artifact-exists-action@v0
        id: check-artifact-exists
        with:
          name: dist-and-coverage-artifacts
      - uses: actions/download-artifact@v3
        if: steps.check-artifact-exists.outputs.exists == 'true'
        with:
          name: dist-and-coverage-artifacts
          path: dist/
      - name: Release
        if: steps.check-artifact-exists.outputs.exists == 'true'
        run: HUSKY=0 npx nx run-many --target=semantic-release --all --parallel=1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.PAT }}

  docker-build:
    name: Docker Build
    needs: ['release']
    runs-on: ubuntu-latest
    env:
      INPUT_PUSH: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - uses: xSAVIKx/artifact-exists-action@v0
        id: check-artifact-exists
        with:
          name: dist-and-coverage-artifacts
      - uses: actions/download-artifact@v3
        if: steps.check-artifact-exists.outputs.exists == 'true'
        with:
          name: dist-and-coverage-artifacts
          path: dist/
      - name: Publish
        if: steps.check-artifact-exists.outputs.exists == 'true'
        run: npx nx affected --target=container --all --parallel=2 --configuration=ci
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
